# Generated by Django 3.2.5 on 2021-07-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.surveyuser')),
            ],
        ),
    ]
