# Generated by Django 3.2.5 on 2021-07-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_questions_surveyresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=60)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.questions')),
            ],
        ),
    ]
