# Generated by Django 3.2.5 on 2021-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210729_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Android', 'Android')], default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.BooleanField(default=True),
        ),
    ]
