# Generated by Django 3.2.5 on 2021-08-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210729_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('R', 'R'), ('A', 'A'), ('I', 'I'), ('S', 'S'), ('E', 'E'), ('C', 'C')], default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
