# Generated by Django 3.2.5 on 2021-08-15 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_surveyuser_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='result',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='survey_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.surveyuser'),
        ),
    ]
